<?php

namespace Proyecto2Bundle\Repository;

/**
 * VueloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VueloRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedById()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM Proyecto2Bundle:Vuelo p ORDER BY p.idvuelo DESC'
            )
            ->getResult();
    }
}
