Proyecto2Bundle\Entity\Cliente:
    type: entity
    repositoryClass: Proyecto2Bundle\Repository\ClienteRepository
    table: cliente
    id:
        idcliente:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombres:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        apellidos:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
        direccion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        direccionFacturacion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: direccion_facturacion
        modoPago:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: modo_pago
        nacimiento:
            type: date
            nullable: true
    lifecycleCallbacks: {  }
