Proyecto2Bundle\Entity\Hospedaje:
    type: entity
    table: hospedaje
    indexes:
        IDX_D0926DF6C339883F:
            columns:
                - idsuite
        IDX_D0926DF6D55632C0:
            columns:
                - idhotel
        IDX_D0926DF62B18C94B:
            columns:
                - idcliente
    id:
        idhospedaje:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        dias:
            type: integer
            nullable: false
            options:
                unsigned: false
        total:
            type: float
            nullable: true
            precision: 10
            scale: 0
    oneToOne:
        idsuite:
            targetEntity: Suite
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idsuite:
                    referencedColumnName: idsuite
            orphanRemoval: false
        idhotel:
            targetEntity: Hotel
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idhotel:
                    referencedColumnName: idhotel
            orphanRemoval: false
        idcliente:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcliente:
                    referencedColumnName: idcliente
            orphanRemoval: false
    lifecycleCallbacks: {  }
