Proyecto2Bundle\Entity\Pago:
    type: entity
    table: pago
    indexes:
        idx_f4df5f3e2b18c94b:
            columns:
                - idcliente
    id:
        idpago:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        monto:
            type: float
            nullable: true
            precision: 10
            scale: 0
        cupon:
            type: float
            nullable: true
            precision: 10
            scale: 0
        total:
            type: float
            nullable: true
            precision: 10
            scale: 0
    manyToOne:
        idcliente:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcliente:
                    referencedColumnName: idcliente
            orphanRemoval: false
    lifecycleCallbacks: {  }
