Proyecto2Bundle\Entity\Tarifa:
    type: entity
    table: tarifa
    id:
        idtarifa:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        clase:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        precio:
            type: float
            nullable: true
            precision: 10
            scale: 0
    lifecycleCallbacks: {  }
