Proyecto2Bundle\Entity\Vuelo:
    type: entity
    table: vuelo
    indexes:
        IDX_B608E37516F9B4BE:
            columns:
                - idorigen
        IDX_B608E3755EF21C94:
            columns:
                - iddestino
        IDX_B608E3756EBC1872:
            columns:
                - idtarifa
        IDX_B608E375AED28132:
            columns:
                - idasiento
        IDX_B608E375C7897C55:
            columns:
                - idreserva
        IDX_B608E375F548F121:
            columns:
                - idavion
    id:
        idvuelo:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        fechahora:
            type: datetime
            nullable: true
    oneToOne:
        idorigen:
            targetEntity: Aeropuerto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idorigen:
                    referencedColumnName: idaeropuerto
            orphanRemoval: false
        iddestino:
            targetEntity: Aeropuerto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                iddestino:
                    referencedColumnName: idaeropuerto
            orphanRemoval: false
        idasiento:
            targetEntity: Asiento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idasiento:
                    referencedColumnName: idasiento
            orphanRemoval: false
        idreserva:
            targetEntity: Reserva
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idreserva:
                    referencedColumnName: idreserva
            orphanRemoval: false
        idavion:
            targetEntity: Avion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idavion:
                    referencedColumnName: idavion
            orphanRemoval: false
    manyToOne:
        idtarifa:
            targetEntity: Tarifa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idtarifa:
                    referencedColumnName: idtarifa
            orphanRemoval: false
    lifecycleCallbacks: {  }
