Proyecto2Bundle\Entity\Vuelo:
    type: entity
    repositoryClass: Proyecto2Bundle\Repository\VueloRepository
    table: vuelo
    indexes:
        IDX_B608E375DF819071:
            columns:
                - iddisponibles
        IDX_B608E3752B18C94B:
            columns:
                - idcliente
    id:
        idvuelo:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        cupon:
            type: float
            nullable: true
            precision: 10
            scale: 0
        total:
            type: float
            nullable: true
            precision: 10
            scale: 0
    manyToOne:
        iddisponibles:
            targetEntity: Disponibles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                iddisponibles:
                    referencedColumnName: iddisponibles
            orphanRemoval: false
        idcliente:
            targetEntity: Cliente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcliente:
                    referencedColumnName: idcliente
            orphanRemoval: false
    lifecycleCallbacks: {  }
